/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c9c6c2",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#454747",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5d5f5f",
        "on-secondary": "#ffffff",
        "on-background": "#1c1b1b",
        "surface-bright": "#fcf8f8",
        "on-secondary-fixed": "#1c1c19",
        "tertiary-container": "#ffffff",
        "on-primary-container": "#747676",
        "on-tertiary-fixed-variant": "#454747",
        "outline": "#747878",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#747676",
        "surface-container-highest": "#e5e2e1",
        "surface-container-high": "#ebe7e7",
        "surface-dim": "#ddd9d9",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1a1c1c",
        "primary": "#5d5f5f",
        "on-error-container": "#93000a",
        "inverse-primary": "#c6c6c7",
        "surface-variant": "#e5e2e1",
        "inverse-on-surface": "#f4f0ef",
        "surface-container": "#f1edec",
        "secondary-fixed": "#e5e2dd",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444748",
        "on-surface": "#1c1b1b",
        "surface": "#fcf8f8",
        "tertiary-fixed": "#e2e2e2",
        "outline-variant": "#c4c7c8",
        "on-secondary-fixed-variant": "#474743",
        "secondary-container": "#e5e2dd",
        "primary-fixed": "#e2e2e2",
        "primary-container": "#ffffff",
        "secondary": "#5f5e5b",
        "background": "#fcf8f8",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-container": "#656461",
        "tertiary": "#5d5f5f",
        "error-container": "#ffdad6",
        "success": "#3d8a4e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "unit": "8px",
        "margin-desktop": "64px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-md": ["Bodoni Moda", "serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "display-lg-mobile": ["Bodoni Moda", "serif"],
        "display-sm": ["Bodoni Moda", "serif"],
        "display-md": ["Bodoni Moda", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "headline-sm": ["Bodoni Moda", "serif"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "0.03em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-sm": ["30px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-md": ["52px", { lineHeight: "1.1", letterSpacing: "0.03em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }]
      },
      maxWidth: {
        "container-max": "1440px"
      }
    },
  },
  plugins: [],
}
